# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LabMenu(object):
    def setupUi(self, LabMenu):
        LabMenu.setObjectName("LabMenu")
        LabMenu.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(30)
        LabMenu.setFont(font)
        self.centralwidget = QtWidgets.QWidget(LabMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.menulabel = QtWidgets.QLabel(self.centralwidget)
        self.menulabel.setGeometry(QtCore.QRect(220, 40, 371, 281))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.menulabel.setFont(font)
        self.menulabel.setObjectName("menulabel")
        self.SHOPButton = QtWidgets.QPushButton(self.centralwidget)
        self.SHOPButton.setGeometry(QtCore.QRect(320, 350, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SHOPButton.setFont(font)
        self.SHOPButton.setObjectName("SHOPButton")
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(320, 380, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ExitButton.setFont(font)
        self.ExitButton.setObjectName("ExitButton")
        self.ReceiptLabel = QtWidgets.QLabel(self.centralwidget)
        self.ReceiptLabel.setGeometry(QtCore.QRect(270, 40, 241, 241))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ReceiptLabel.setFont(font)
        self.ReceiptLabel.setText("")
        self.ReceiptLabel.setObjectName("ReceiptLabel")
        self.Remove_cookie = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_cookie.setGeometry(QtCore.QRect(550, 180, 51, 31))
        self.Remove_cookie.setObjectName("Remove_cookie")
        self.Remove_sandwich = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_sandwich.setGeometry(QtCore.QRect(550, 230, 51, 31))
        self.Remove_sandwich.setObjectName("Remove_sandwich")
        self.Remove_water = QtWidgets.QPushButton(self.centralwidget)
        self.Remove_water.setGeometry(QtCore.QRect(550, 290, 51, 31))
        self.Remove_water.setObjectName("Remove_water")
        self.Add_cookie = QtWidgets.QPushButton(self.centralwidget)
        self.Add_cookie.setGeometry(QtCore.QRect(150, 180, 51, 31))
        self.Add_cookie.setObjectName("Add_cookie")
        self.Add_sandwich = QtWidgets.QPushButton(self.centralwidget)
        self.Add_sandwich.setGeometry(QtCore.QRect(150, 230, 51, 31))
        self.Add_sandwich.setObjectName("Add_sandwich")
        self.Add_water = QtWidgets.QPushButton(self.centralwidget)
        self.Add_water.setGeometry(QtCore.QRect(150, 280, 51, 31))
        self.Add_water.setObjectName("Add_water")
        LabMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LabMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        LabMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LabMenu)
        self.statusbar.setObjectName("statusbar")
        LabMenu.setStatusBar(self.statusbar)

        self.retranslateUi(LabMenu)
        QtCore.QMetaObject.connectSlotsByName(LabMenu)

    def retranslateUi(self, LabMenu):
        _translate = QtCore.QCoreApplication.translate
        LabMenu.setWindowTitle(_translate("LabMenu", "MainWindow"))
        self.menulabel.setText(_translate("LabMenu", "Welcome"))
        self.SHOPButton.setText(_translate("LabMenu", "SHOP"))
        self.ExitButton.setText(_translate("LabMenu", "EXIT"))
        self.Remove_cookie.setText(_translate("LabMenu", "-"))
        self.Remove_sandwich.setText(_translate("LabMenu", "-"))
        self.Remove_water.setText(_translate("LabMenu", "-"))
        self.Add_cookie.setText(_translate("LabMenu", "+"))
        self.Add_sandwich.setText(_translate("LabMenu", "+"))
        self.Add_water.setText(_translate("LabMenu", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LabMenu = QtWidgets.QMainWindow()
    ui = Ui_LabMenu()
    ui.setupUi(LabMenu)
    LabMenu.show()
    sys.exit(app.exec_())
